name = "spinogambino-casinobonus-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casinobonus.com"
HMAC_KEY = "a301a0ae9806d00929e48c46e0dc7b1f1e54ff46fb5b9b4abac0ce28dc58debd"
COOKIE_NAME = "594"
PLAY_PATH = "discover"
BUTTON_ID = "pd4bebfebd7aff9178b577debdfb596af"
GATE_SALT = "c0089d1e05bb7b1b"
